- name: Initialize k8s cluster
  become: yes
  hosts: masters
  tasks:
  - name: Initialize k8s cluster
    ansible.builtin.shell: |
      kubeadm token create --print-join-command > /tmp/join_command.sh

- name: Transfer join file from masters to local
  hosts: masters
  become: yes
  tasks:
  - name: Transfer join file from masters to local
    ansible.builtin.fetch:
      src: /tmp/join_command.sh
      dest: /tmp/from_masters/join_command.sh
      flat: yes

- name: Transfer join file from local to slaves
  become: yes
  hosts: slaves
  tasks:
  - name: Transfer join file from local to slaves
    copy:
      src: /tmp/from_masters/join_command.sh
      dest: /tmp/join_command.sh

- name: Join slaves
  become: yes
  hosts: slaves
  tasks:
  - name: Join slaves
    ansible.builtin.shell: |
      chmod +x /tmp/join_command.sh
      /tmp/join_command.sh